name: Build Jenkins Job with Plugin Installation, JCasC and Custom Steps

# on:
#   push:
#     branches: [ master ]

jobs:
  build_jenkins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Java
        run: |
          java --version

      - uses: actions/checkout@v4
      - name: Install Plugins
        run: |
          chmod +x plugin_script.sh
          ./plugin_script.sh

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  

      - name: Install python-jenkins
        run: |
          python3 -m pip install python-jenkins

      - name: Fetching Jobs from Server A
        run: python3 fetch.py

      - name: Run/Build/Configure your jobs to Server B
        run: python3 test1.py

      - uses: actions/checkout@v4
      - name: Restarting After Instlling Plugins and 
        run: |
            chmod +x restart_script.sh
            ./restart_script.sh
      
      #     java -jar jenkins-cli.jar -s http://13.201.4.9:8080/ -auth @creds install-plugin -f plugins.txt 
      # - name: Upload JCasC Configuration
      #   run: |
      #     java -jar jenkins-cli.jar -s http://13.201.4.9:8080/ -auth @creds upload-configuration jcasc.yaml
      # - name: Reload Jenkins Configuration
      #   run: |
      #     java -jar jenkins-cli.jar -s http://13.201.4.9:8080/ -auth @creds safe-restarts
