name: Build Jenkins Job with Plugin Installation, JCasC and Custom Steps

on:
  push:
    branches: [ master ]

jobs:
  build_jenkins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Java
        run: |
          java --version
          python3 --version
      - uses: actions/checkout@v4
      - name: Install Jenkins CLI
        run: |
          wget -q -O - https://get.jenkins.io/cli | bash
      - name: Install Plugins
        run: |
          java -jar jenkins-cli.jar -s http://localhost:8080/ -auth @creds install-plugin -f plugins.txt
      - name: Upload JCasC Configuration
        run: |
          java -jar jenkins-cli.jar -s http://localhost:8080/ -auth @creds upload-configuration jcasc.yaml
      - name: Reload Jenkins Configuration
        run: |
          java -jar jenkins-cli.jar -s http://localhost:8080/ -auth @creds safe-restart
      - name: Run Custom Script (Optional)  
        run: python3 test1.py
