name: Build Jenkins Job with Plugin Installation, JCasC and Custom Steps

on:
  push:
    branches: [ master ]

jobs:
  build_jenkins:
    runs-on: ubuntu-latest
    env:
      JENKINS_URL: http://localhost:8080/
    steps:
      - uses: actions/checkout@v3
      - name: Download Java
        run: |
          java --version
      - uses: actions/checkout@v3
      - name: Install Jenkins CLI
        run: |
          wget -q -O - https://get.jenkins.io/cli | bash
      - name: Install Plugins
        run: |
          java -jar jenkins-cli.jar -s --url ${{ env.JENKINS_URL }} --user ${{ secrets.JENKINS_USER }} --password ${{ secrets.JENKINS_TOKEN }} install-plugin -f plugins.txt
      - name: Upload JCasC Configuration
        run: |
          java -jar jenkins-cli.jar -s --url ${{ env.JENKINS_URL }} --user ${{ secrets.JENKINS_USER }} --password ${{ secrets.JENKINS_TOKEN }} upload-configuration jcasc.yaml
      - name: Reload Jenkins Configuration
        run: |
          java -jar jenkins-cli.jar -s --url ${{ env.JENKINS_URL }} --user ${{ secrets.JENKINS_USER }} --password ${{ secrets.JENKINS_TOKEN }} safe-restart
      - name: Run Custom Script (Optional)  
        run: python3 test1.py
